spring:
  cloud:
    config:
      name: spring-cloud-config-client
      profile: dev
      uri: http://10.3.99.29:8888
      label: master
#server:
#  port: 7777
#spring:
#  application:
#    name: spring-cloud-eureka-client
#eureka:
